### ISSUE TITLE
Javascript dependencies in the front end

### ISSUE THREAD

**Issue by asifkazi** [microsoft/Microsoft-Fabric-workload-development-sample#106]
There are some obsolete packaged libraries with the front end which shows up on the UI as errors. Can we please fix the dependencies and code to avoid getting the front end errors.

![image](https://github.com/user-attachments/assets/fed9de35-7b1e-4bc2-b008-f5b3c7f9da04)

**Comment by ramizsha** [comment]
We are working on this - you can just close this in the meanwhile (right top corner).
