### ISSUE TITLE
Sample app "Double the result" disabled on data entry

### ISSUE THREAD

**Issue by asifkazi** [microsoft/Microsoft-Fabric-workload-development-sample#107]
Step to repro:
A) In the Sample Item edit, when the page first opens the "Double the result" is enabled.
B) Then selecting any item on the page or entering any value to the textboxes the dialog box gets disabled.

Has been communicated to me as an annoyance by multiple developers.

Again just a nitpick, not really critical in the grand scheme of things, but worth fixing the experience for new developers who are going through the app to avoid confusion

![image](https://github.com/user-attachments/assets/57e4be65-d014-4313-9d8f-724661ade432)

**Comment by ramizsha** [comment]
Thanks @asifkazi,
We'll take a look.
