### ISSUE TITLE
Update item fails

### ISSUE THREAD

**Issue by dhrumil83** [microsoft/Microsoft-Fabric-workload-development-sample#113]
This was working till last week, but failing today.
Note: This happens in both dev and test mode

**Dev Mode:**
Create item works, and I can put a breakpoint in the BE code.
The update item does not even go to the BE. Seems to fail in fabric with 500 Internal Server error.
Request: https://wabi-west-us-redirect.analysis.windows.net/metadata/artifacts/8d37ad1c-fef5-4c30-9923-c3df77184537
Response: {"code":"NullReferenceException","message":"Object reference not set to an instance of an object."}

**Test mode:**
https://wabi-west-us-redirect.analysis.windows.net/metadata/artifacts/76872fa6-42fc-431d-9fcb-ff5e9471b59d
Response: {"code":"NullReferenceException","message":"Object reference not set to an instance of an object."}

Maybe related to this: https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/issues/87#issuecomment-2371319966

**Comment by michal-mano** [comment]
The issue should be fixed, could you confirm that you don't have a problem anymore @dhrumil83 ?

**Comment by dhrumil83** [comment]
Thanks. 
Confirmed, works now.
