### ISSUE TITLE
DevGateway fails to run with MissingAssets error

### ISSUE THREAD

**Issue by GnPatton** [microsoft/Microsoft-Fabric-workload-development-sample#132]
When I try to run DevGateway it fails with the next error: `{"errorCode":"Target","message":"MissingAssets"},{"errorCode":"Message","message":"Certain items reference images that are not found in the designated assets folder.`. It complains that some assets from assets folders are missing even though they are present there and I didn't touch them.

**Comment by selimslab** [comment]
Had the same problem, please make sure you follow the latest version of this repo
