### ISSUE TITLE
Newly created item does not display in the workspace till you refresh the browser

### ISSUE THREAD

**Issue by dhrumil83** [microsoft/Microsoft-Fabric-workload-development-sample#133]
Call [`callItemCreate`](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/blob/main/Frontend/src/controller/SampleWorkloadController.ts#L433) then go to the workspace page.

New Item does not display will you refresh the page.

**Comment by michal-mano** [comment]
Hi,
Could you elaborate on how to reproduce this?
When an item is created, you should navigate to the item.
This is the behavior for all items in Fabric.
Are you saying that after you navigate to the item page and then navigate back to the workspace, the item doesn't appear?

**Comment by dhrumil83** [comment]
We currently have a different workflow.
User is already in the application => they author a map(add layers from lakehouse, add styling, etc) => once they are happy, they save  the map/create new item. At this point we don't navigate to the page since they are already in the application and might want to make more additional edits.
Now go to workspace, and the item does not appear till you refresh the page.

Note: If I call create => then call update and then go the workspace the new item is there.

**Comment by anitamayorov** [comment]
Hi @dhrumil83, 
We do not support this behaviour therefore for now the workaround is, as you mentioned, to manually refresh the page.
No ETA.

Thanks
