### ISSUE TITLE
"Empty iframeId" error in @ms-fabric/workload-client when running sample workload locally

### ISSUE THREAD

**Issue by jkw-statsig** [microsoft/Microsoft-Fabric-workload-development-sample#135]
Trying to get started by running the sample workload on localhost, but hitting this error when running `npm start`.

Error is happening within the `@ms-fabric/workload-client` package. Getting rid of the `assert` gets rid of the error, but only loads an empty page. Is this a known issue? Any idea how to fix it?

![Image](https://github.com/user-attachments/assets/9b090c62-b1df-44d8-8e81-7cb735c53a93)

**Comment by atefsaw** [comment]
Hi @jkw-statsig ,

The frontend sample is designed to run within an iFrame in the Fabric portal, as described [here](https://learn.microsoft.com/en-us/fabric/workload-development-kit/workload-environment).

To be able to view your frontend, navigate to Portal, enable both the development tenant setting and the Developer mode (As described [here](https://learn.microsoft.com/en-us/fabric/workload-development-kit/environment-setup)), and then you should be able to see your workload Frontend.

Please let me know if you have more questions.

**Comment by atefsaw** [comment]
Thanks for confirming! I’ll go ahead and close this issue now. If you have any further questions or run into any other issues, feel free to reopen it or open a new one.
