### ISSUE TITLE
Error running DevGateway.

### ISSUE THREAD

**Issue by pietrobr** [microsoft/Microsoft-Fabric-workload-development-sample#14]
I'm trying to start the DevGateway. After the authentication step I get the error in the image below.

I'm not sure how I can troubleshooting the error to find out what configuration (probably) I made wrong.

Any help could be appreciated

![thumbnail_image](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/2890569/981e1a3d-2d39-407e-a86b-c198e1a8a2a8)

**Comment by box-turtle** [comment]
Don't know if it is the same issue (the error message is not helpful), but when I received that error message it was because my workload name (and app id uri) did not follow the convention `Org.<workloadName>` similar to the `Org.WorkloadSample` that is used in the demo docs.

**Comment by willwainwright** [comment]
I also had the same issue when the workload name was not consistent across all files. I had renamed it but some still had the sample workload name. It must also match the app id uri

**Comment by ramizsha** [comment]
Hi @pietrobr,
What's the resourceId in your workloadManifest.xml?
Please note that we have some rules regarding the format of the resourceId (see https://github.com/microsoft/Microsoft-Fabric-developer-sample/blob/main/Authentication/Setup.md#configuring-your-application-in-microsoft-entra-id---manual)

**Comment by ramizsha** [comment]
Hi @pietrobr ,
Please make sure that you have configured the resourceId in your workloadManifest.xml.
See the rules that must apply on the resourceId [here](https://learn.microsoft.com/en-us/fabric/workload-development-kit/authentication-tutorial#configure-your-application-in-microsoft-entra-id).

**Comment by pietrobr** [comment]
I solved using the sample workload name everywhere. Thanks
