### ISSUE TITLE
Issues with Workloads Hub and Workload Validation error message

### ISSUE THREAD

**Issue by tdraganidis** [microsoft/Microsoft-Fabric-workload-development-sample#143]
Trying to start using the Fabric WDK, but having a lot of issues with Fabric portal and Workloads.
- The workloads hub is not shown on the left-side pane as it supposed.
- When I turned on the option `Turn on developer mode to enable your local hosted workload on Fabric.` under the Workloads Developer mode section in Developer Settings, I started getting the following error:

![Image](https://github.com/user-attachments/assets/03ca95d5-9da4-4aaa-8e89-76839578cb53)

I don't have any custom workloads, I have just entered the Fabric portal.

- I'm Fabric Administrator, Capacity Administrator and also have turned on all the Tenant Settings related to Workloads.
  - Followed also these [setup instructions](https://learn.microsoft.com/en-us/fabric/workload-development-kit/environment-setup)

Any suggestions on what I can do to start seeing the Workloads Hub and what this error is all about?

**Comment by anitamayorov** [comment]
Hi @tdraganidis, 
The workload hub is visible only when you have public workloads or activated to tenant workloads. 
Regarding the notification - when you turn on the developer mode experience, it searches for your local server to fetch your local workload. If you still haven't done the 'npm start' stage here https://learn.microsoft.com/en-us/fabric/workload-development-kit/quickstart-sample#set-up-the-sample-project then Fabric portal fails to locate the server and displays this notification.

**Comment by tdraganidis** [comment]
> Hi [@tdraganidis](https://github.com/tdraganidis), The workload hub is visible only when you have public workloads or activated to tenant workloads. Regarding the notification - when you turn on the developer mode experience, it searches for your local server to fetch your local workload. If you still haven't done the 'npm start' stage here https://learn.microsoft.com/en-us/fabric/workload-development-kit/quickstart-sample#set-up-the-sample-project then Fabric portal fails to locate the server and displays this notification.

Hi @anitamayorov, 
thanks for your prompt reply!
- The notification issue has been fixed after applying your suggestion (to first `npm start` my local project).
- The Workload Hub is still not visible
  - I don't have any of my workloads publicly published. 
  - I have enabled the tenant settings from the Fabric Portal like in the screenshot below. 
![Image](https://github.com/user-attachments/assets/952ba4ad-c793-44b5-9edd-b2d159841bf1)

Am I missing any other settings that should be applied in another place?
