### ISSUE TITLE
How to get the DEV_AAD credentials to run only the FE?

### ISSUE THREAD

**Issue by NaveenkumarMD** [microsoft/Microsoft-Fabric-workload-development-sample#145]
The webpack dev server started successfully, but it throws and error saying iFrame is Empty.
![Image](https://github.com/user-attachments/assets/a59edf0b-2c94-476e-a255-dd315373b3a7)

```batchfile

# The workload name should be alligned with the name defined in the WorkloadmManifest.xml
WORKLOAD_NAME=Org.WorkloadSample
WORKLOAD_BE_URL=https://localhost:5001

# These properties are used only in FE dev mode and are used to override AADConfig for obtaining AAD token in the client. 
# In non-FE dev mode, these values are taken from WorkloadmManifest.xml.
# Read more in authentication wiki
DEV_AAD_CONFIG_AUDIENCE=
DEV_AAD_CONFIG_APPID=
DEV_AAD_CONFIG_REDIRECT_URI=http://localhost:60006/close
```

I believe I should fill these creds to get the FE running. Where can I find these creds in the fabric account?

**Comment by NaveenkumarMD** [comment]
https://learn.microsoft.com/en-us/fabric/workload-development-kit/authentication-tutorial#configure-your-application-in-microsoft-entra-id-manually Followed this to get the creds.
Updated the .env.dev with the creds, but still i'm getting the same error.

**Comment by tdraganidis** [comment]
I also get the same error as @NaveenkumarMD ! I have set the settings as described in the documentation.

**Comment by anitamayorov** [comment]
Hi @NaveenkumarMD @tdraganidis , can you please clarify your scenario? 
1. Were you able to connect successfully using DevGateway? 
2. Do you have a running local workload backend?
3. The frontend part runs successfully after `npm start`?

**Comment by anitamayorov** [comment]
Hi @tdraganidis , yes, the sample project has a UI only shown in Fabric portal, so when you run `npm start` you will see an empty page even if the server runs successfully.
