### ISSUE TITLE
'Id' issue with various buttons in the latest code

### ISSUE THREAD

**Issue by asifkazi** [microsoft/Microsoft-Fabric-workload-development-sample#172]
Getting consistent errors in the front-end app for "id" 

e.g. Navigate to authentication page, and other such buttons scattered throughout the app.

![Image](https://github.com/user-attachments/assets/96812751-0dea-41e3-b0e6-dffc44b177f4)

**Comment by asifkazi** [comment]
@ReenuSaluja

**Comment by shaym83** [comment]
@asifkazi - are you using the sample workload? do you have any changes on top of it?

**Comment by asifkazi** [comment]
Zero changes to sample workload other than updating the config files. Can confirm other users on my team are seeing the same thing.  Fresh git clone and ONLY starting front end.

**Comment by asifkazi** [comment]
OK I will go through it and setup the backend as well, but its only
accessing the Frontend ONLY experience.

**Comment by vinayslumel** [comment]
If you want to use the authentication page functionalities, you have to create an item and use it from the created item.

**Comment by shaym83** [comment]
See answer from Vinay

**Comment by asifkazi** [comment]
I can confirm that this issue still exists, I have a fully functional app, I still get this javascript error on the "navigate to authentication page".

**Comment by asifkazi** [comment]
Have a partner who is getting the exact same issue, with a fully functional app. We can create the item and work with the item but the "Front End Only Playground" is broken
