### ISSUE TITLE
WorkLoad Validation Error in fabric

### ISSUE THREAD

**Issue by tushar586** [microsoft/Microsoft-Fabric-workload-development-sample#18]
I have enabled both "Fabric Developer Mode" and "Capacity Admin Can Develop Additional Workloads." However, the workload icon does not appear on the Fabric screen, and an error message is displayed.

![Screenshot 2024-06-20 135708](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/118589891/6f4d0d12-559c-4a47-911e-8abc7b7df290)

When i am uploading a sample workload getting error 

![Screenshot 2024-06-20 141447](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/118589891/a3bac9d0-8d41-42f0-b839-91f9697dba2b)

**Comment by anitamayorov** [comment]
Hi @tushar586,

The 'validation error' you see means you have an error with one of your XMLs or Json files that define your Workload, Product and Items. 
You can see in console logs for developer scenario + Upload request's response in network traces for test scenario: 
In those you will be able to see more detailed info regarding the specific parameters causing the error. 

Furthermore, you can look at the XSD files + schema.json files in our Sample repository to understand the expected structure.
