### ISSUE TITLE
Fabric: Unable to create sample workload item

### ISSUE THREAD

**Issue by Lashin23** [microsoft/Microsoft-Fabric-workload-development-sample#19]
I'm trying to run sample workload solution and creating new sample workload item, but getting below error - 
![image](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/173355225/bf0b3ac4-de3b-49c0-a690-803f29075082)

Error showing up as "ArtifactInputFailure:

![image](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/173355225/cbf6111e-3004-4a36-8cf2-288d22199398)

![image](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/173355225/770c4b20-03d4-4a65-8b07-e97cf8b36104)

![image](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/173355225/10f1f119-9084-4939-9a09-a40334753ac2)

![image](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/173355225/d6ce13d7-2473-4801-be61-cf813c82ea37)

Steps followed from https://learn.microsoft.com/en-us/fabric/workload-development-kit/extensibility-back-end

**Comment by dhrumil83** [comment]
I had to comment out this line for the sample to work: https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/blob/main/Backend/src/Services/AuthenticationService.cs#L166

**Comment by anitamayorov** [comment]
Hi @Lashin23,

Were you able to register successfully your developer workload using the DevGateway? 
Are you trying to create an item on a workspace registered on the same capacity defined in workload-dev-mode.json file?

**Comment by Lashin23** [comment]
Couldn't perform this step - Run the Microsoft.Fabric.Workload.DevGateway.exe application located in Backend\DevGateway
as I'm unable to find DevGateway under Backend directoty from cloned solution

**Comment by dhrumil83** [comment]
Copy the zip file to that location: https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/issues/12

**Comment by anitamayorov** [comment]
Hi @Lashin23,

You can download the DevGateway from Microsoft's Download Center https://www.microsoft.com/en-us/download/details.aspx?id=105993

We will update our documentation for this step.

**Comment by Lashin23** [comment]
After successful run of DevGateway getting below error:
![image](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/assets/173355225/b7161648-a63c-422f-964d-4c4d435fa792)

**Comment by anitamayorov** [comment]
Hi @Lashin23,

To verify - 
1. Were you able to register your workload successfully using DevGateway?
2. Do you have a running Workload (If you use the Sample project in Visual Studio - is it running? It should act as your local BE for the different CRUD calls sent by Fabric)
3. Are you trying to create an item on a workspace attached to the same capacity specified in your workload-dev-mode.json file?

Also, please provide requestIds for the failed network calls ('/artifacts').

**Comment by SanketK9831** [comment]
Hi @anitamayorov,

This link to download gateway is breaking. https://www.microsoft.com/en-us/download/details.aspx?id=105993

**Comment by selimslab** [comment]
Had the same problem, solved by creating a new workspace in lowercase and restarting the devgateway

**Comment by vishnu01** [comment]
I'm facing this issue. 

I have verified all the steps mentioned below.

- Were you able to register your workload successfully using DevGateway?

- Do you have a running Workload (If you use the Sample project in Visual Studio - is it running? It should act as your local BE for the different CRUD calls sent by Fabric)

- Are you trying to create an item on a workspace attached to the same capacity specified in your workload-dev-mode.json file?

**Comment by SanchanaMohankumar** [comment]
Hi @vishnu01, 
Were you able to fix the issue from your side?
