### ISSUE TITLE
No way to get current workspace from workload item editor page

### ISSUE THREAD

**Issue by box-turtle** [microsoft/Microsoft-Fabric-workload-development-sample#20]
When Fabric loads your workload item it uses the URL

```
  /myWorkloadPath/{itemId}
```

So you have access to the item id. But I am stumped on how I might retrieve the current workspace id inside the workload item editor page. Is there any API to retrieve the current workspace id?

Was hoping to see some guidance here in the sample:

https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/blob/main/Frontend/src/components/SampleWorkloadEditor/SampleWorkloadEditor.tsx#L649

**Comment by anitamayorov** [comment]
Hi @box-turtle,

You can use getItem in ItemCrudAPI to get the item details, part of the response is the foldetObjectId representing the workspace id the item is part of.

**Comment by box-turtle** [comment]
ah ok. folder = workspace in this case.
