### ISSUE TITLE
Fabric Workload Client npm package transitively depends on React

### ISSUE THREAD

**Issue by q-benwillis** [microsoft/Microsoft-Fabric-workload-development-sample#34]
It seems that the @ms-fabric/workload-client npm package has a dependency on "@fluentui/react-components" which has peer dependencies on React. We're not using React in our custom Workload, we're using Angular instead. It looks like the package only uses BrandVariants from "@fluentui/tokens" which doesnt have the any dependencies on React itself so the dependency on React seems unnecessary.

Is this dependency strictly necessary as it introduces quite a lot of bloat? Would it be possible to update the dependency for this package to avoid brining in the transitive dependency on React?

In the short term we'll just add these dependencies:
```
"react": "^17.0.2",
"react-dom": "^17.0.2",
```

**Comment by anitamayorov** [comment]
Hi @q-benwillis,
Thanks for raising this - we are aware of this dependency and have a working task on that - no ETA yet.
