### ISSUE TITLE
Type check of Fabric Workload client fails

### ISSUE THREAD

**Issue by q-benwillis** [microsoft/Microsoft-Fabric-workload-development-sample#35]
I'm seeing the following error when building our custom Fabric Workload frontend:
```
Error: node_modules/@ms-fabric/workload-client/src/workload-client.d.ts:2888:11 - error TS2430: Interface 'OpenPageConfig' incorrectly extends interface 'OpenUIConfig'.
  Property 'workloadName' is optional in type 'OpenPageConfig' but required in type 'OpenUIConfig'.

2888 interface OpenPageConfig extends OpenUIConfig {
```
Seems that there's a type issue in the `@ms-fabric/workload-client` npm package.

I'm working around this by disabling library type checking with `"skipLibCheck": true` in my tsconfig.json.

**Comment by ramizsha** [comment]
This is by-design.
Developers should always set skipLibCheck/skipDefaultLibCheck to true for d.ts in node_modules.

**Comment by q-benwillis** [comment]
Okay, I guess the logical question is when using `OpenPageConfig` is `workloadName` actually optional or is it required?

**Comment by ramizsha** [comment]
It's marked as deprecated and you should not pass it.
See https://learn.microsoft.com/en-us/javascript/api/@ms-fabric/workload-client/openpageconfig?view=fabric-extensibility-js-latest.
