### ISSUE TITLE
Fabric UX docs are inaccurate

### ISSUE THREAD

**Issue by q-nicolechoi** [microsoft/Microsoft-Fabric-workload-development-sample#55]
There are some discrepancies between the docs and the actual code, and I cannot use property binding in some cases. Here are some examples.

### 1. Button
To disable an icon button, the example code in [docs](https://ambitious-cliff-0c8148010.2.azurestaticapps.net/?path=/docs/reactwrappers_react-web-component-wrappers-fluent-wrappers-button--docs) shows
```
<fluent-button
  appearance="primary"
  disabledFocusable
  iconOnly
  shape="round"
  size="medium"
>
  Button
</fluent-button>
```

But after many trial and errors, it should be `disabled` and `icon-Only` instead of `disabledFocusable` and `iconOnly`.
![image](https://github.com/user-attachments/assets/c524b97c-ebce-4d90-9943-74d0f8dfd630)
```
<fluent-button appearance="primary" shape="round" size="medium" iconOnly>
    iconOnly
</fluent-button>
<fluent-button appearance="primary" shape="round" size="medium" icon-Only>
    icon-Only
</fluent-button>
<fluent-button appearance="primary" shape="round" size="medium" disabledFocusable>
    disabledFocusable
</fluent-button>
<fluent-button appearance="primary" shape="round" size="medium" disabled>
    Disabled
</fluent-button>
```

It will also be useful if we can use property binding, or is there an alternative way to dynamically to enable/disable a button?
![image](https://github.com/user-attachments/assets/5ae7909c-78c9-4d54-89f5-ce828ca5f3f4)

### 2. MenuItem
The [docs](https://ambitious-cliff-0c8148010.2.azurestaticapps.net/?path=/docs/angularwrappers_angular-web-component-wrappers-fluent-wrappers-menuitem--docs) suggests it is possible to dynamically disable a menu item. But I cannot disable it at all:
![image](https://github.com/user-attachments/assets/8fbf98fe-895b-4d12-b46b-679de5049ec3)
```
<fluent-menu-list>
    <fluent-menu-item role="menuitem" [disabled]="true">
        Item 1
    </fluent-menu-item>
    <fluent-menu-item role="menuitem">
        Item 2
    </fluent-menu-item>
    <fluent-menu-item role="menuitem">
        Item 3
    </fluent-menu-item>
</fluent-menu-list>
```
These also don't work:
![image](https://github.com/user-attachments/assets/972fd0a8-b3d0-47a2-8bec-200bcfb60d4f)

**Comment by anitamayorov** [comment]
Hi @q-nicolechoi, 
Those inconsistencies were discussed with Fabric UX team, and they will fix it, no ETA yet.
