### ISSUE TITLE
Weird DevGateway behaivour

### ISSUE THREAD

**Issue by q-benwillis** [microsoft/Microsoft-Fabric-workload-development-sample#77]
We've noticed some weird behaivour in DevGateway.

If two members of the team are running DevGateway and locally developing a new Fabric workload we've noticed that sometimes the requests from one person get directed to another persons gateway.

For example if person A creates a new Workload Item the REST request gets directed to person B's local DevGateway. This seems to happen even if person A creates the Workload Item in their own personal workspace. It also looks like the request is never sent to person A's local machine.

Is this expected behaviour? If so is there a way to restrict it so that my requests only go to my local machine as it makes developing quite difficult with multiple people.

**Comment by ramizsha** [comment]
@q-benwillis This might happen if 2 people are using the same workload name and the same capacity. (not related to the workspace).
For now, each person developing should work on a different capacity or they can use the same capacity but with different workload names.
