### ISSUE TITLE
Microsoft.Fabric.Workload.DevGateway.exe Window won't open

### ISSUE THREAD

**Issue by ladparth** [microsoft/Microsoft-Fabric-workload-development-sample#78]
I have placed workload-dev-mode.json in the root folder C:\ and updated it with capacityId and the path to the package. However, when i run Microsoft.Fabric.Workload.DevGateway.exe, i see window opens up and close on its own like a window flicker. Is there anything i am missing here?

Here's how i have updated my path to package: 
```
{
	"CapacityGuid": "CapacityIDCopiedFromAdminPortal",
	"ManifestPackageFilePath": "C:\\Users\\user\\Source\\Repos\\Microsoft-Fabric-workload-development-sample\\Backend\\src\\bin\\Debug\\ManifestPackage.1.0.0.nupkg",
	"WorkloadEndpointURL": "http://127.0.0.1:5000/workload"
}

```

**Comment by ramizsha** [comment]
You can see an error if you run the devgateway from an CMD instead of double clicking on it.

**Comment by ladparth** [comment]
Thanks a lot @ramizsha. I really appreciate your suggestion. Here's what i found, i had newer versions but i needed  
Framework: 'Microsoft.AspNetCore.App', version '6.0.0' (x64)
