### ISSUE TITLE
Unable to resolve weird DevGateway behaviour

### ISSUE THREAD

**Issue by q-bhargsharma** [microsoft/Microsoft-Fabric-workload-development-sample#79]
We previously raised [this issue](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/issues/77) and were advised that the weird behaviour in DevGateway was due to multiple users using the same WorkloadName on the same capacity.

Since then we have tried to use a different WorkloadName for a user but we are unable to do any operations in Fabric (i.e. create a new item). We see the error below when trying to create a new item. Checked that after refreshing the page, the new item is never created.

![image](https://github.com/user-attachments/assets/910699a2-7da3-4e5d-acc2-23a141ed8ddd)

The manifest file at `http://localhost:60006/manifests` seems to be exactly the same as before except for the new WorkloadName being substituted in.

Should having a new WorkloadName on the same capacity resolve the issues we are seeing? Is there anything else to try? Unfortunately it is a big blocker for us as it is becoming impossible for multiple people to develop at the same time.

**Comment by ramizsha** [comment]
@q-bhargsharma some questions:
1. Did the registeration of the workload using dev gateway succeed?
2. Did you change the workload name in the backend manifest as well? (Workloadmanifest.xml)

**Comment by q-bhargsharma** [comment]
Hi 👋🏽 
1. Yes the registration did succeed as I can see the newly registered workloadoon the Fabric homepage and click on it/open it.
2. Yes I did change the workload name in the backend manifest. The 2 changed manifests are shown in the screenshot below.

<details>

![image](https://github.com/user-attachments/assets/1a9c2508-c681-4dbb-beb4-660c195cc5b7)

</details>

**Comment by ramizsha** [comment]
@q-bhargsharma I see that the first request of "/artifacts" returns 500.
Can you please share the request-id of that request along with a link to this issue and send it to our support alias? (ILDCWLSupport@microsoft.com)
You can find the request id in the response header of the call.
