### ISSUE TITLE
Error when acquiring access token

### ISSUE THREAD

**Issue by q-benwillis** [microsoft/Microsoft-Fabric-workload-development-sample#83]
I'm developing a new Fabric workload and am trying to acquire a new access token using the [Auth Client API](https://learn.microsoft.com/en-us/javascript/api/%40ms-fabric/workload-client/authclientapi?view=fabric-extensibility-js-latest).

This is my code:
```
const token = await this.workloadClient.client.auth.acquireAccessToken(params).catch(err => {
  console.error("Failed to retrieve token", err);
});
```
where `params` is:
```
{
    "additionalScopesToConsent": [
        ".default"
    ],
    "claimsForConditionalAccessPolicy": null
}
```
Unfortunately this is failing and all I'm seeing in the logs is `Failed to retrieve token {error: 0}`. Is there any way I can get more information on why this is failing?

**Comment by yonadiv** [comment]
solved offline, it is transient: solved by adding the url parameter clientSideAuth=1 and then it stopped failing even without the parameter.
