### ISSUE TITLE
Cannot find module when after upgrading @fabric-msft/fabric-angular

### ISSUE THREAD

**Issue by q-nicolechoi** [microsoft/Microsoft-Fabric-workload-development-sample#88]
After upgrading `@fabric-msft/fabric-angular` from `1.0.0-beta` to `1.0.4-beta` (also tried `1.0.4-beta.1`), we get the following error when trying to import a module
```
import { LoadingButtonProxyModule } from '@fabric-msft/fabric-angular';

Cannot find module '@fabric-msft/fabric-angular' or its corresponding type declarations.
```
![image](https://github.com/user-attachments/assets/499f61a5-3166-4c7b-a134-89aae38a3700)

From the [docs page](https://ambitious-cliff-0c8148010.2.azurestaticapps.net/?path=/docs/angularwrappers_about--docs) I found a Stackblitz example [here](https://stackblitz.com/edit/stackblitz-starters-5x2c4k?file=package.json%3AL13) which has the same issue with the most recent version.

**Comment by amirshwar** [comment]
This issue is related to another package which is not included in this workload sample.
Kindly contact the owners of this package for further support - [@fabric-msft/fabric-angular](https://www.npmjs.com/package/@fabric-msft/fabric-angular?activeTab=readme)
