### ISSUE TITLE
Navigate to product home page from workload app

### ISSUE THREAD

**Issue by q-nicolechoi** [microsoft/Microsoft-Fabric-workload-development-sample#98]
Is there a way to navigate from the workload app to the product home page (`https://app.fabric.microsoft.com/home?experience=XXX`)?

I tried using the [NavigationAPI](https://learn.microsoft.com/en-us/javascript/api/@ms-fabric/workload-client/navigationapi?view=fabric-extensibility-js-latest#@ms-fabric-workload-client-navigationapi-navigate) like so but I'm not sure if it is the correct way:
```
private workloadClient: WorkloadClientAPI = createWorkloadClient();
this.workloadClient.client.navigation.navigate('host', { path: '/home'  }).catch(err => console.error(err));

// error:
{error: '3p extensions cannot navigate to host target'}
```

Also tried target="workload" but it takes me to `https://app.fabric.microsoft.com/workloads/XXX?experience=XXX`, where this path `/workloads/XXX` does not exist in our workload
```
this.client.client.navigation.navigate('workload', { path: '' }).catch(err => console.error(err));
```

**Comment by ramizsha** [comment]
Nope, this is not supported. (as the error suggests).
